version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Entering the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build phase completed

artifacts:
  files:
    - target/spring-pipeline-example.jar
  discard-paths: yes