name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag spring-docker-app:$(date +%s)

    - name: Run the docker image
      run: docker run --publish 8080:8080 spring-docker-app
